#!/usr/bin/env bash

# TODO
all()
{
	read -r
	echo "$REPLY"
}
task()
{
	echo 'task'
}
project()
{
	echo 'project'
}
while getopts ":atp" opt; do
	case $opt in
		a) all; break;;
		t) task; break;;
		p) project; break;;
		h) echo 'this is help';;
		\?) echo "Wrong option";;
		:) echo 'no optoion provided';;
	esac

done
# No option provided
if [ "$OPTIND" -eq 1]; then
	#TODO:
fi
#DIR_PATH="$(find ~ -name "checker_suite" -type d)"
#
#declare -A suites
#echo "Select suite option:"
#count=1
#
## Looping thro the suites
#for dir in $DIR_PATH/*; do
#	if [ -d "$dir" ]; then
#		suite=$(basename $dir)
#		suites[$count]="$suite"
#		echo "$count- $suite" && ((count++))
#	fi
#
#done
#read -r suite
#
## select a suite option
#case $suite in
#	1) echo "${suites[1]}"; DIR_PATH="DIR_PATH/${suites[1]}";;
#	2) echo "${suites[2]}"; DIR_PATH="DIR_PATH/${suites[2]}";;
#	*) echo Wrong option; checker;;
#esac
#
## Look for a top level checker insdie the selected suite
#
#
##for file in $(find "${DIR_PATH}/c_suite/0x05-pointers_arrays_strings/checker" -type f -name "*.sh"); do
##	if [ -x "$file" ]; then
##		. "$file"
##	fi
##done
